auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:categories/:title.html
timezone: Asia/Shanghai

title: Ango's Pages
url: http://angos.github.io
baseurl:
feed: /rss.xml

author_info: <a href="http://angos.github.io/">Ango's Pages</a>
description: Write the Code. Change the World.
webjs: /assets/scripts
webcss: /assets/styles
webimg: /assets/images
